from backend.app.tools.spatial_ops import (
    list_available_layers,
    get_layer_schema,
    buffer_layer,
    spatial_intersection,
    spatial_difference,
    spatial_filter_within,
    delete_layer,
    delete_layers_matching,
    calculate_evacuation_route,
    resolve_or_create_cardinal_hub,
    synthesize_regional_hazard_zones,
    generate_voronoi_catchments,
    generate_isochrone_reachability,
    aggregate_catchment_metrics,
    generate_multi_ring_buffers,
)
from backend.app.tools.sql_runner import run_attribute_sql, run_spatial_sql

ALL_SPATIAL_TOOLS = [
    list_available_layers,
    get_layer_schema,
    buffer_layer,
    spatial_intersection,
    spatial_difference,
    spatial_filter_within,
    delete_layer,
    delete_layers_matching,
    calculate_evacuation_route,
    resolve_or_create_cardinal_hub,
    synthesize_regional_hazard_zones,
    generate_voronoi_catchments,
    generate_isochrone_reachability,
    aggregate_catchment_metrics,
    generate_multi_ring_buffers,
    run_spatial_sql,
    run_spatial_sql,
    run_attribute_sql,
]

__all__ = [
    "ALL_SPATIAL_TOOLS",
    "list_available_layers",
    "get_layer_schema",
    "buffer_layer",
    "spatial_intersection",
    "spatial_difference",
    "spatial_filter_within",
    "delete_layer",
    "delete_layers_matching",
    "calculate_evacuation_route",
    "resolve_or_create_cardinal_hub",
    "synthesize_regional_hazard_zones",
    "generate_voronoi_catchments",
    "generate_isochrone_reachability",
    "aggregate_catchment_metrics",
    "generate_multi_ring_buffers",
    "run_spatial_sql",
    "run_attribute_sql",
]